stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - Litmus-chaos-testing
  - cleanup
  - deploy
azure-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 755 ./script/azure
    - ./script/azure

  artifacts:
    paths:
      - azoebs_aks_name/

openebs-deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - azure-cluster
  script: 
   - echo "deploying OpenEBS on Azure"
   - ls
   - chmod 775 ./script/infra-setup
   - ./script/infra-setup
  
  artifacts:
    paths:
      - azure/

percona-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/stateful-app-deploy
   - ./script/stateful-app-deploy

  artifacts:
    paths:
      - azure/

apps-aws-deploy-cstor:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-AWS-Started"
   - chmod 775 ./script/stateful-app-deploy-cstor
   - ./script/stateful-app-deploy-cstor
  artifacts:
    paths:
      - aws-cstor/

Litmus-Chaos:
  image: atulabhi/kops:v8
  dependencies:
    - openebs-deploy
  stage: Litmus-chaos-testing
  script:
   - echo " Introducing-Chaos"
   - mkdir ~/.kube
   - cp  azure/config ~/.kube/config 
   - kubectl create -f https://raw.githubusercontent.com/atulabhi/litmus/v0.7-RC1/apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yaml
   - chmod 755 ./script/chaos
   - ./script/chaos

Litmus-Chaos-cstor:
  image: atulabhi/kops:v8
  dependencies:
    - openebs-deploy
  stage: Litmus-chaos-testing
  script:
   - echo " Introducing-Chaos"
   - mkdir ~/.kube
   - cp  azure/config ~/.kube/config 
   - kubectl create -f https://raw.githubusercontent.com/atulabhi/litmus/cstor-v0.7-RC1/apps/percona/chaos/openebs_cstor_target_failure/run_litmus_test.yaml
   - chmod +x ./script/chaoscstor
   - ./script/chaoscstor



cleanup-azure:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - azure-cluster
  stage: cleanup
  script: 
    - chmod 755 ./script/azure-cleanup
    - ./script/azure-cleanup
